// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npxhioadifkrhoaewnrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5weGhpb2FkaWZrcmhvYWV3bnJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NjM1MDMsImV4cCI6MjA3MDQzOTUwM30.GyjnlGF0GGerfvcLQ-cSfdf5WW8l1lgVaTpTMPtX9WU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});